os:
  - linux
  - osx
language: c
script:
    - make clean
    - make
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make deb          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make zip          ; fi
