os:
  - linux
  - osx
  - windows
language: c
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install make curl ; 
      curl https://curl.haxx.se/windows/dl-7.63.0/curl-7.63.0-win32-mingw.zip ; 
      unzip curl-7.63.0-win32-mingw.zip  ;
    fi
script:
    - make clean
    - make
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make deb          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make zip          ; fi
